################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import jpype



ReferenceIdentifier = jpype.JClass('org.opengis.referencing.ReferenceIdentifier')

NoSuchIdentifierException = jpype.JClass('org.opengis.referencing.NoSuchIdentifierException')

NoSuchAuthorityCodeException = jpype.JClass('org.opengis.referencing.NoSuchAuthorityCodeException')

ObjectFactory = jpype.JClass('org.opengis.referencing.ObjectFactory')

AuthorityFactory = jpype.JClass('org.opengis.referencing.AuthorityFactory')

ReferenceSystem = jpype.JClass('org.opengis.referencing.ReferenceSystem')

IdentifiedObject = jpype.JClass('org.opengis.referencing.IdentifiedObject')

Factory = jpype.JClass('org.opengis.referencing.Factory')

FactoryException = jpype.JClass('org.opengis.referencing.FactoryException')

SpatialReferenceSystemUsingGeographicIdentifier = jpype.JClass('org.opengis.referencing.SpatialReferenceSystemUsingGeographicIdentifier')